comment/urls.py
from django.urls import path
from .views import (
    postDetail,
    commentList,
    commentCreate,
    replyCreate
)

urlpatterns = [
    path('<slug>/', postDetail, name='post-detail'),
    path('<slug>/comment', commentList, name='comment-list'),
    path('comment/create',commentCreate , name='comment-create'),
    path('comment/<id>/reply',replyCreate , name='reply-create'),

]

comments/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('comment.urls')),
]

comment/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField(blank=True, null=True,)
    slug = models.SlugField(max_length=64)

    def __str__(self):
        return self.title

class Comment(models.Model):
    username = models.CharField(max_length=64,null=False, blank=False, default="Andanh")
    description = models.TextField(max_length=500,)
    commented_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.username} : {self.post} {self.description}"

class Reply(models.Model):
    target = models.ForeignKey(Comment, on_delete=models.CASCADE)
    username = models.CharField(max_length=64,null=False, blank=False, default="Andanh")
    description = models.TextField(max_length=500,)
    commented_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.username} : {self.target.post}"

comment/forms.py
from django import forms
from .models import Comment, Reply

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['username', 'description']
        

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['username', 'description']

comment/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Comment, Post, Reply
from .forms import CommentForm, ReplyForm
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User

# Create your views here.


def postDetail(request, slug):
    post = get_object_or_404(Post,slug=slug)
    comments = Comment.objects.filter(post=post)
    
    formcomment = CommentForm(request.POST or None)
    replyform = ReplyForm(request.POST or None)

    if request.method == "POST":
        target_id = request.POST.get("target"," ")
        if formcomment.is_valid():
            comment = formcomment.save(commit=False)
            comment.post = post
            if request.user.is_authenticated:
                comment.username = request.user.username
            comment.save()
        if replyform.is_valid():
            try:
                target = Comment.objects.get(id=target_id)
                reply = replyform.save(commit=False)
                reply.target = target
                reply.save()
                # reply.save()
                # print(reply)
                # reply.target = Comment.objects.get(id=)
            except:
                ...
                
    return render(request, 'comment/post-detail.html', {
        'post': post,
        'comments': comments,
        'formcomment': formcomment,
        'replyform': replyform,
    })


def commentList(request, slug):
    post = Post.objects.get(slug=slug)
    comments = Comment.objects.filter(post=post)

    return render(request, 'comment/comment-list.html', {
        'comments': comments,
        'form': CommentForm()
    })

def commentCreate(request):
    form = CommentForm()
    
    context = {
        'formcomment' : form
    }
    return render(request, 'comment/comment-create.html',context)

def replyCreate(request, id):
    form = ReplyForm()
    target_id = id
    context = {
        'replyform' : form,
        'target_id' : target_id
    }
    return render(request, 'comment/reply-create.html', context)

comment/templates/comment/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="#">
    <script src="https://unpkg.com/htmx.org@1.8.2"></script>

    <title>Document</title>
</head>
<body>
    
    {% block content %}
    
    {% endblock content %}
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{csrf_token}}';
        })
    </script>
    </body>
</html>

comment/templates/comment/comment-create.html
<div hx-target="this" hx-swap="outterHTML">
    <form method="post" action=".">
        {% csrf_token %}    
        {{form.as_p}}
        <button>Submit</button>
    </form>
</div>

comment/templates/comment/comment-list.html
<ol>
{% for comment in comments %}
    <li>{{comment.username}} : {{comment.description}}</li>
{% endfor %}
</ol>
    

{% include 'comment/comment-create.html' %}

comment/templates/comment/post-detail.html
{% extends 'comment/base.html' %}
{% block content %}
{{post.title}}
{{post.description}}

{% for comment in comments  %}
<div id="{{comment.id}}" hx-target="this" hx-swap="outterHTML">
    <p>{{comment.username}} ({{comment.commented_at|timesince}}) : {{comment.description}} <button hx-get="{% url 'reply-create' comment.id %}" hx-swap="beforeend" hx-target="#replyform{{comment.id}}">Reply</button>
    </p>
    <div id="replyform{{comment.id}}">
    </div>
</div>
    {% for reply in comment.reply_set.all %}
    <p style="margin-left: 20px; color: red;">{{reply.username}} ({{reply.commented_at|timesince}}) : {{reply.description}}</p>
    {% endfor %}

{% endfor %}
<button hx-get="{% url 'comment-create' %}" hx-swap="beforeend" hx-target="#commentform">Add comment</button>
<div id="commentform">
</div>



{% endblock content %}

comment/templates/comment/reply-create.html
<div hx-target="this" hx-swap="outterHTML">
    <form method="post" action=".">
        {% csrf_token %}
        {% if user.is_authenticated %}
            {{replyform}}
        {% else %}
        {{replyform.as_p}}
        {% endif %}
        <input type="hidden" name="target" value="{{target_id}}">
        <button>Submit</button>
    </form>
</div>